name: edtechnica
favicon: null
layout_spectrum: 0.20627891342155635
typography_spectrum: 0.16017052810639143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6739409426227212
  lightness: 0.09095928189344704
  saturation: 0.1516925331670791
  rhythmicContrast: 0.9528605311643332
purpose: []
